#include "actors/items/utils.java"
#include "actors/utils/sentry.java"
#include "actors/utils/support.java"
#include "actors/spots/healthspot.java"
#include "actors/spots/armorspot.java"
#include "actors/spots/ammospot.java"
#include "actors/items/test.java"
// #include "actors/items.java"
// #include "actors/itemspot.txt"
// #include "actors/allies.txt"